### PR TITLE
Bug Fix: Name sometimes falls under 2nd child not last-child

### PR DESCRIPTION
**Pull request by muchai-mercy**
Update your profile to:
- Show Business opportunities you provide
- Or open to job opportunities

attempt to scrape your profile or anyone's that shows such data, there is an additional div of class: `pv-top-card-row` which would be the last-child. 
To provide the correct `name` field whethere anyone has such data or not, use the 2nd child

### CODE REVIEW

**Comment by dbecker215** [comment]
Is there a specific reason why this hasn't been merged? I'm interested in having a fix for names as well.

**Comment by leonardiwagner** [comment]
Thank you for the collaboration @muchai-mercy 

@dbecker215 It's hard to test new changes, I have to do all tests manually. Please let me know if you guys have any interest in maintaining this project so I can include more people here to be able to push new changes faster.

I receive so many requests about this project (most of them directly into my personal e-mail) and sometimes I'm lost on priorities, I wasn't aware how important this was, sorry :cry: 

Now it was merged and published, please update your version to `v1.0.13`

**Comment by dbecker215** [comment]
No worries. I appreciate the response. My group would like to help out with this repo as we expect to be using it for a while. You can add myself and @kf6kjg.

**Comment by kf6kjg** [comment]
We’ll do what we can. We’ve a fair bit of experience with automation and testing.

**Pull request merged**
