### PR TITLE
Fix Login

### PR DESCRIPTION
**Pull request by KristianLauttamus**
I managed to fix the login bug, by switching a few lines of code

### CODE REVIEW

**Comment by leonardiwagner** [comment]
Hi @KristianLauttamus what bug? I couldn't find that on issues, please inform the issue, thanks.

**Comment by tdooner** [comment]
Hi, we're hitting this too. The bug is that LinkedIn seems to be running an A/B test to roll out a new homepage with different login fields:

image

**Comment by leonardiwagner** [comment]
Alright, thanks for the update @tdooner , I'm gonna merge it

**Comment by a10kiloham** [comment]
This would be better if there were conditional checks to see which version present. It seems rather fragile to depend on this current url without checking version of the login style

**Comment by tdooner** [comment]
@a10kiloham - I agree in principle, though, it appears that in this case the inconsistency comes from the fact that the *homepage* is sometimes different. This branch updates the `loginUrl` to avoid the homepage entirely and go directly to the username/password login page. I believe that page is identical between both versions.

**Comment by leonardiwagner** [comment]
@KristianLauttamus , @tdooner first of all, thank you for the layout change feedback, I just released a new version with this fix, including @KristianLauttamus PR, thanks again!
- v1.0.4 is now supported with this new login fix

While testing I also found a new LinkedIn update, they changed their profile layout, then  besides not finding a div for profile page identification (and breaking scrapedin), it was not possible to read basic data such as name, headline, location.. plus, the summary is now separated into a new section, have you guys  faced this problem as well?

Screenshot from 2019-05-15 12-04-13

If so, I also fixed that (reading the new layout #22 ), and published:
- [v1.0.5](https://github.com/linkedtales/scrapedin/releases/tag/v1.0.5) new login + new 

so @a10kiloham you can still use v1.0.3 if this new login breaks for you, otherwise you can move to v1.0.4 or even to v1.0.5 if the new profile layout is also displaying for you.

The worst cenario is: old login + new profile, then I recommend you to move back to v1.0.3 and apply #22 on it

Please report any other issue! :smile:

**Pull request merged**
